email: mail@example.com
ingressClass: nginx
privateKeySecretRef: letsencrypt

httpIssuer:
  enabled: true

route53Issuer:
  enabled: true
  region: eu-west-1

route53ExternalIssuer:
  enabled: false
  region: eu-west-1
  keyID: keyID
  secretName: secretName
  secretKey: aws_secret_access_key

clouddns:
  enabled: false
  project: not-provided

cloudflare:
  enabled: false
  email: not-provided
  secretNamespace: cert-manager
  secretName: cloudflare-api
  secretKey: api-key
  createSecret: false
  apiKey: not-provided