{{- if .Values.clouddns.enabled }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: dns-clouddns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ .Values.privateKeySecretRef }}
    solvers:
    - dns01:
        clouddns:
          project: {{ .Values.clouddns.project }}
    dns01:
      providers:
      - name: clouddns
        clouddns:
          project: {{ .Values.clouddns.project }}
---
{{- end }}