{{- if .Values.route53Issuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dns-route53
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: {{ .Values.privateKeySecretRef }}
    solvers:
    - dns01:
        route53:
          region: {{ .Values.route53Issuer.region }}
---
{{- end }}